plant_uml_path: /Users/gerkulesov35/IdeaProjects/mirea-config/git-dependency-visualizer/plantuml-1.2024.7.jar
repository_path: /Users/gerkulesov35/IdeaProjects/mirea-config/kotlin-shell
start_date: 2023-01-01
branch: main